CREATE TABLE IF NOT EXISTS cart (
    id BIGSERIAL PRIMARY KEY,
    create_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(225) NOT NULL,
    total_price DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_item (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    cart_id INTEGER NOT NULL,
    FOREIGN KEY (cart_id) REFERENCES cart(id)
);